// c4-vue3-ts-quasar/src/layouts/Header.vue
<template>
  <header>
    <div class="q-pa-md q-gutter-y-sm">
      <q-toolbar>
        <q-toolbar-title>
          <q-img src="/logo.png" alt="logo" width="120px" />
        </q-toolbar-title>

        <q-icon
          class="q-mr-md"
          :color="isOnline ? 'positive' : 'negative'"
          name="fa-solid fa-network-wired"
          size="xs"
        />
        <q-btn outline dense class="q-px-sm" color="primary" icon="fa-brands fa-github" label="GitHub" :href="url" />
      </q-toolbar>
    </div>
  </header>
</template>

<script setup lang="ts">
  import { storeToRefs } from 'pinia'
  import { useMainStore } from '../store'

  const mainStore = useMainStore()
  const { isOnline } = storeToRefs(mainStore)

  // GitHub URL
  const url = 'https://github.com/kensoz/Rrea-client-collection/tree/master/c4-vue3-ts-quasar'
</script>

// c2-react18-ts-mui/src/components/Header.tsx
import { useState, useEffect } from 'react'
import PubSub from 'pubsub-js'

import AppBar from '@mui/material/AppBar'
import Box from '@mui/material/Box'
import Toolbar from '@mui/material/Toolbar'
import Button from '@mui/material/Button'
import { GitHub, Language } from '@mui/icons-material'

export default function Header(): JSX.Element {
  // GitHub URL
  const url: string = 'https://github.com/kensoz/Rrea-client-collection/tree/master/c2-react18-ts-mui'

  // React Hooks
  const [isOnline, changeIsOnline] = useState<boolean>()

  useEffect((): (() => void) => {
    PubSub.subscribe('network', (_, data: boolean): void => {
      changeIsOnline(data)
    })

    return (): void => {
      PubSub.unsubscribe('network')
    }
  })

  return (
    <Box sx={{ flexGrow: 1 }}>
      <AppBar position="static" color="transparent" sx={{ boxShadow: 0, my: 1 }}>
        <Toolbar variant="dense">
          <Box sx={{ display: 'flex', flexGrow: 1 }}>
            <img src="/logo.png" alt="logo" width={135} />
          </Box>

          <Box sx={{ display: 'flex', alignItems: 'center', flexDirection: 'row' }}>
            <Language color={isOnline ? 'success' : 'error'} sx={{ mr: 2 }} />

            <Button variant="outlined" startIcon={<GitHub />} href={url}>
              GitHub
            </Button>
          </Box>
        </Toolbar>
      </AppBar>
    </Box>
  )
}
